### ISSUE TITLE
Code error via unit.cpp

### ISSUE THREAD

**Issue by leewheel** [Frostshake/TrinityCoreClassic#54]
in unit.cpp line 13612 has a code error "std no to_underlying"
`if (std::to_underlying(m_fieldNotifyFlags) & flags[index] ||`

**Comment by Frostshake** [comment]
Fixed with fb3ac3c135473ea56a4c582b0a0fa027c10820f8

**Comment by leewheel** [comment]
Great!  Happy new year!
